name: ✨ 機能要求
description: 新機能や既存機能の改善を提案
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 機能要求
        
        新機能や既存機能の改善についての提案を記載してください。
        
  - type: dropdown
    id: type
    attributes:
      label: 要求タイプ
      description: この要求の種類を選択してください
      options:
        - 新機能
        - 既存機能の改善
        - パフォーマンス向上
        - セキュリティ強化
        - 開発体験の向上
    validations:
      required: true
      
  - type: dropdown
    id: service
    attributes:
      label: 対象サービス
      description: この機能に関連するサービスを選択してください
      options:
        - api
        - batch
        - pkg/logger
        - 全体アーキテクチャ
        - 開発ツール・CI/CD
        - その他
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: この機能で解決したい課題や背景を記載してください
      placeholder: "現在こんな問題があって..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能や改善を提案するかを記載してください
      placeholder: "こんな機能があれば解決できると思います..."
    validations:
      required: true
      
  - type: textarea
    id: technical_details
    attributes:
      label: 技術的詳細
      description: 実装に関する技術的な詳細や考慮事項があれば記載してください
      placeholder: |
        - 使用する技術・ライブラリ:
        - データベース変更の必要性:
        - API変更の影響:
        - パフォーマンスへの影響:
        
  - type: textarea
    id: api_design
    attributes:
      label: API設計案（該当する場合）
      description: 新しいAPIエンドポイントや変更が必要な場合、設計案を記載してください
      render: yaml
      placeholder: |
        # 例
        GET /api/v1/new-endpoint
        Request:
          - parameter: value
        Response:
          - field: description
          
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の優先度を選択してください
      options:
        - High - 早急に必要
        - Medium - 近いうちに必要
        - Low - あると良い
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に考えられる解決策があれば記載してください
      
  - type: checkboxes
    id: checklist
    attributes:
      label: チェックリスト
      description: 以下の項目を確認してください
      options:
        - label: 既存のissueに同様の要求がないことを確認した
          required: true
        - label: この機能が現在のアーキテクチャに適合するかを考慮した
          required: true
        - label: 可能であれば関係者と事前に議論した