name: Test and Lint

on:
  push:
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [services/api, services/batch]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        working-directory: ${{ matrix.module }}
        run: go mod download

      - name: Run tests
        working-directory: ${{ matrix.module }}
        run: go test -v ./...

  lint:
    name: Lint (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [services/api, services/batch, pkg/logger]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        working-directory: ${{ matrix.module }}
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --config=${{ github.workspace }}/.golangci.yml
          working-directory: ${{ matrix.module }}
        # linter導入直後は一度すべての指摘を潰すまでエラーにはしなくても良い
        # continue-on-error: true
